name: Periodic Hello

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello!"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v5
        with:
          # Check the following URLs one by one sequentially
          url: https://fs-pokedex-autumn-sea-9744.fly.dev/